trigger:
  - master

pool:
  vmImage: ubuntu-latest

variables:
- group: tokens

steps:
 - script: |
     mvn verify package sonar:sonar -Dsonar.host.url=https://sonarcloud.io/ \
     -Dsonar.organization=hemanth3183 -Dsonar.projectKey=hemanth3183_azdevops-java \
     -Dsonar.token=$(SONAR_TOKEN)
     sudo apt update
     sudo apt install curl jq
     quality_status=$(curl -s -u $(SONAR_TOKEN): \
     https://sonarcloud.io/api/qualitygates/project_status?projectKey=hemanth3183_azdevops-java | \
     jq -r '.projectStatus.status')