apiVersion: apps/v1
kind: Deployment
metadata:
  name: vulnado-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vulnado
  template:
    metadata:
      labels:
        app: vulnado
    spec:
      containers:
      - name: vulnado
        image: 145988340565.dkr.ecr.us-west-2.amazonaws.com/vulnado
        imagePullPolicy: Always
        ports:
        - containerPort: 8085
# service type loadbalancer       
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: vulnado
    k8s-app: vulnado
  name: vulnado
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 8085
  type: LoadBalancer
  selector:
    app: vulnado
