trigger:
- main

pool:
  vmImage: ubuntu-latest

variables:
  - group: tokens

steps:
- script: |
    wget https://github.com/zaproxy/zaproxy/releases/download/v2.16.0/ZAP_2.16.0_Linux.tar.gz
    tar -xvf ZAP_2.16.0_Linux.tar.gz
    cd ZAP_2.16.0
    ./zap.sh -cmd -quickurl https://www.example.com -quickprogress -quickout /home/vsts/work/1/a/zap_report.html 
  displayName: "DAST ZAP Scan"
  
- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: zap_report.html
    
